config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index" except: %i[edit]
  resources :restaurants, only: %i[index new create show destroy update] do
    post :create_review
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, acceptance: { accept: ['chinese','italian', 'japanese', 'french', 'belgian'] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, acceptance: { accept: (0..5).to_a }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: :show

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def create_review
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :show, status: :unprocessable_entity
    end
  end

  def show
    @review = Review.new
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<h1>RESTAURANTS</h1>
<%= simple_form_for(restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>

app/views/restaurants/index.html.erb
<% @restaurants.each do |restaurant| %>
  <div class="row">
    <div class="col-12">
      <h2>* <%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
      <% link_to "Delete", restaurant_path(restaurant),
        data: {
          turbo_method: :delete,
          turbo_confirm: 'Are you sure?'
        }
      %>
    </div>
  </div>
<% end %>

app/views/restaurants/new.html.erb
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1 class="mb-3"><%= @restaurant.name %></h1>
<p><strong>Address: </strong><%= @restaurant.address %></p>
<p><strong>Category: </strong><%= @restaurant.category.capitalize %></p>
<div id="reviews">
  <p><strong>Reviews: </strong></p>
  <ul class="list-group">
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item"><%= review.content %> (<%= "*" * review.rating %>)</li>
    <% end %>
  </ul>
  <br>
  <div class="card bg-light mb-3">
  <div class="card-header">Add Review</div>
  <div class="card-body">
    <%= render "/reviews/form", restaurant: @restaurant, review: @review %>
  </div>
</div>

app/views/reviews/_form.html.erb
<H1>REVIEW</H1>
<%= simple_form_for [restaurant, review], url: restaurant_create_review_path(restaurant) do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "Save Rev", class: "btn btn-primary" %>
  <% end %>
1